spring:
  datasource:
    password: timecard
    username: timecard
    url: jdbc:mysql://localhost:3306/timecard
    
    
logging:
  level:
    root: warn
    '[com.workercareclinic]': debug